package:
  name: fsttrpgpersonalitymodule
  version: 0.1.3

build:
 number: 1
 string: alpha

source:
  git_url: https://github.com/Krypticdator/FSTTRPGPersonality.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
about:
  summary: Fuzion Roleplayin System personality module